include:
  - path: ./infra.yaml
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - weatherkey=${weatherkey}
      - redisPassword=${redisPassword}
      - redisPORT=${redisPORT}
      - redisURL=${redisURL}
      - redisUser=${redisUser}
      - JAVA_OPTS=-Xms128m -Xmx256m

