spring:
  application:
    name: WeatherAPI
  thymeleaf:
    check-template-location: false
server:
  address: 0.0.0.0
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.weatherapi: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"

